# Generated by Django 5.2.17 on 2026-08-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('store_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
